app_home:
  path: /
  controller: App\Controller\HomeController::index

app_blog:
  path: /blog
  controller: App\Controller\HomeController::blog

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

app_post_show:
  path: /post/show/{id}
  controller: App\Controller\PostController::show

app_admin_show:
  path: /profile/show/{id}
  controller: App\Controller\AdminController::show

app_admin_edit:
    path: /profile/edit/{id}
    controller: App\Controller\AdminController::edit

app_admin_reset_pass:
  path: /profile/{id}/password_reset
  controller: App\Controller\AdminController::passwordReset